# Generated by Django 5.2.8 on 2025-11-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SicarRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(db_column='numero_car', max_length=43, unique=True, verbose_name='Número do CAR')),
                ('status', models.CharField(max_length=50)),
                ('geo_coordinates', models.TextField(db_column='coordenadas_geograficas', verbose_name='Coordenadas Geográficas')),
            ],
            options={
                'verbose_name': 'Registro do SICAR',
                'verbose_name_plural': 'Registros do SICAR',
                'db_table': 'tb_registro_sicar',
            },
        ),
    ]
