# Generated by Django 5.2.8 on 2025-11-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sicarrecord',
            name='hash_id',
        ),
        migrations.AddField(
            model_name='sicarrecord',
            name='last_update',
            field=models.DateField(blank=True, db_column='ultima_atualizacao', null=True, verbose_name='Última Atualização'),
        ),
    ]
