# Generated by Django 5.2.8 on 2025-11-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_system', '0002_remove_sicarrecord_hash_id_sicarrecord_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='sicarrecord',
            name='geometry_type',
            field=models.CharField(blank=True, db_column='tipo_geometria', max_length=50, null=True, verbose_name='Tipo de Geometria'),
        ),
    ]
