# Generated by Django 5.2.8 on 2025-11-18 23:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_system', '0003_sicarrecord_geometry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sicarrecord',
            name='geometry_new',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_tmp', null=True, srid=4326),
        ),
    ]
