# Generated by Django 5.2.8 on 2025-11-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_system', '0004_sicarrecord_geometry_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sicarrecord',
            name='geometry_type',
        ),
        migrations.AddField(
            model_name='sicarrecord',
            name='area_ha',
            field=models.FloatField(blank=True, db_column='area_ha', null=True, verbose_name='Área (ha)'),
        ),
        migrations.AddField(
            model_name='sicarrecord',
            name='area_m2',
            field=models.FloatField(blank=True, db_column='area_m2', null=True, verbose_name='Área (m²)'),
        ),
    ]
