# Generated by Django 5.2.8 on 2025-11-19 16:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_system', '0005_remove_sicarrecord_geometry_type_sicarrecord_area_ha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicarrecord',
            name='geometry_new',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_tmp', null=True, srid=4674),
        ),
    ]
