# Generated by Django 5.2.8 on 2025-11-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phytoecology_zip_file', models.FileField(help_text='Arquivo ZIP contendo dados da Área de Fitoecologia.', upload_to='documents/', verbose_name='Documentos Fitoecologia')),
                ('environmental_protection_zip_file', models.FileField(help_text='Arquivo ZIP contendo dados da Área de Proteção Ambiental.', upload_to='documents/', verbose_name='Documentos Proteção Ambiental')),
                ('zoning_zip_file', models.FileField(help_text='Arquivo ZIP contendo dados da Área de Zoneamento.', upload_to='documents/', verbose_name='Documentos Zoneamento')),
                ('sicar_zip_file', models.FileField(help_text='Arquivo ZIP contendo dados da Área SICAR.', upload_to='documents/', verbose_name='Documentos SICAR')),
            ],
            options={
                'verbose_name': 'Gerenciamento de Arquivos',
                'verbose_name_plural': 'Gerenciamento de Arquivos',
                'db_table': 'tb_gerenciamento_arquivos',
            },
        ),
    ]
