# Generated by Django 5.2.8 on 2025-11-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanagement',
            name='indigenous_zip_file',
            field=models.FileField(blank=True, help_text='Arquivo ZIP contendo dados da Área de Terra Indígena.', null=True, upload_to='documents/', verbose_name='Documentos Terra Indígena'),
        ),
    ]
