# Generated by Django 5.2.8 on 2025-11-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalProtectionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(db_column='nome_unidade_conservacao', max_length=100, verbose_name='Nome da Unidade de Conservação')),
                ('domains', models.CharField(db_column='dominios', max_length=100, verbose_name='Domínios')),
                ('class_group', models.CharField(db_column='grupo_classe', max_length=100, verbose_name='Grupo de Classe')),
                ('legal_basis', models.CharField(db_column='fundo_legal', max_length=100, verbose_name='Fundo Legal')),
                ('geo_coordinates', models.TextField(db_column='coordenadas_geograficas', verbose_name='Coordenadas Geográficas')),
            ],
            options={
                'verbose_name': 'Área de APA',
                'verbose_name_plural': 'Áreas de APAs',
                'db_table': 'tb_area_apa',
            },
        ),
        migrations.CreateModel(
            name='PhytoecologyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phyto_name', models.CharField(db_column='nome_fitoecologia', max_length=70, verbose_name='Nome da Fitoecologia')),
                ('geo_coordinates', models.TextField(db_column='coordenadas_geograficas', verbose_name='Coordenadas Geográficas')),
            ],
            options={
                'verbose_name': 'Área de Fitoecologia',
                'verbose_name_plural': 'Áreas de Fitoecologia',
                'db_table': 'tb_area_fitoecologia',
            },
        ),
        migrations.CreateModel(
            name='SicarRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(db_column='numero_car', max_length=43, unique=True, verbose_name='Número do CAR')),
                ('status', models.CharField(max_length=50)),
                ('geo_coordinates', models.TextField(db_column='coordenadas_geograficas', verbose_name='Coordenadas Geográficas')),
            ],
            options={
                'verbose_name': 'Registro do SICAR',
                'verbose_name_plural': 'Registros do SICAR',
                'db_table': 'tb_registro_sicar',
            },
        ),
        migrations.CreateModel(
            name='ZoningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(db_column='nome_zona', max_length=100, verbose_name='Nome da Zona')),
                ('zone_acronym', models.CharField(db_column='sigla_zona', max_length=50, verbose_name='Sigla da Zona')),
                ('geo_coordinates', models.TextField(db_column='coordenadas_geograficas', verbose_name='Coordenadas Geográficas')),
            ],
            options={
                'verbose_name': 'Área de Zoneamento',
                'verbose_name_plural': 'Áreas de Zoneamento',
                'db_table': 'tb_area_zoneamento',
            },
        ),
    ]
