# Generated by Django 5.2.8 on 2025-11-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvironmentalProtectionArea',
        ),
        migrations.DeleteModel(
            name='PhytoecologyArea',
        ),
        migrations.DeleteModel(
            name='SicarRecord',
        ),
        migrations.DeleteModel(
            name='ZoningArea',
        ),
    ]
