# Generated by Django 5.2.8 on 2025-11-12 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalProtectionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_coordinates', models.TextField(db_column='coordenadas_geograficas', verbose_name='Coordenadas Geográficas')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte de Dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em')),
                ('unit_name', models.CharField(db_column='nome_unidade_conservacao', max_length=100, verbose_name='Nome da Unidade de Conservação')),
                ('domains', models.CharField(db_column='dominios', max_length=100, verbose_name='Domínios')),
                ('class_group', models.CharField(db_column='grupo_classe', max_length=100, verbose_name='Grupo de Classe')),
                ('legal_basis', models.CharField(db_column='fundo_legal', max_length=100, verbose_name='Fundo Legal')),
                ('created_by', models.ForeignKey(blank=True, db_column='id_criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, db_column='id_atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Área de APA',
                'verbose_name_plural': 'Áreas de APAs',
                'db_table': 'tb_area_apa',
            },
        ),
        migrations.CreateModel(
            name='PhytoecologyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_coordinates', models.TextField(db_column='coordenadas_geograficas', verbose_name='Coordenadas Geográficas')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte de Dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em')),
                ('phyto_name', models.CharField(db_column='nome_fitoecologia', max_length=70, verbose_name='Nome da Fitoecologia')),
                ('created_by', models.ForeignKey(blank=True, db_column='id_criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, db_column='id_atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Área de Fitoecologia',
                'verbose_name_plural': 'Áreas de Fitoecologia',
                'db_table': 'tb_area_fitoecologia',
            },
        ),
        migrations.CreateModel(
            name='ZoningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_coordinates', models.TextField(db_column='coordenadas_geograficas', verbose_name='Coordenadas Geográficas')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte de Dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em')),
                ('zone_name', models.CharField(db_column='nome_zona', max_length=100, verbose_name='Nome da Zona')),
                ('zone_acronym', models.CharField(db_column='sigla_zona', max_length=50, verbose_name='Sigla da Zona')),
                ('created_by', models.ForeignKey(blank=True, db_column='id_criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, db_column='id_atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Área de Zoneamento',
                'verbose_name_plural': 'Áreas de Zoneamento',
                'db_table': 'tb_area_zoneamento',
            },
        ),
    ]
