# Generated by Django 5.2.8 on 2025-11-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_layers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentalprotectionarea',
            old_name='geo_coordinates',
            new_name='geometry',
        ),
        migrations.RenameField(
            model_name='phytoecologyarea',
            old_name='geo_coordinates',
            new_name='geometry',
        ),
        migrations.RenameField(
            model_name='zoningarea',
            old_name='geo_coordinates',
            new_name='geometry',
        ),
        migrations.AddField(
            model_name='environmentalprotectionarea',
            name='hash_id',
            field=models.CharField(blank=True, db_column='hash_id', max_length=64, null=True, unique=True, verbose_name='Hash ID'),
        ),
    ]
