# Generated by Django 5.2.8 on 2025-11-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_layers', '0002_rename_geo_coordinates_environmentalprotectionarea_geometry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalprotectionarea',
            name='legal_basis',
            field=models.CharField(blank=True, db_column='fundo_legal', max_length=100, null=True, verbose_name='Fundo Legal'),
        ),
    ]
