# Generated by Django 5.2.8 on 2025-11-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_layers', '0003_alter_environmentalprotectionarea_legal_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoningarea',
            name='hash_id',
            field=models.CharField(blank=True, db_column='hash_id', max_length=64, null=True, unique=True, verbose_name='Hash ID'),
        ),
    ]
