# Generated by Django 5.2.8 on 2025-11-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_layers', '0004_zoningarea_hash_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phytoecologyarea',
            name='hash_id',
            field=models.CharField(blank=True, db_column='hash_id', max_length=64, null=True, unique=True, verbose_name='Hash ID'),
        ),
    ]
