# Generated by Django 5.2.8 on 2025-11-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_layers', '0005_phytoecologyarea_hash_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalprotectionarea',
            name='geometry_type',
            field=models.CharField(blank=True, db_column='tipo_geometria', max_length=50, null=True, verbose_name='Tipo de Geometria'),
        ),
        migrations.AddField(
            model_name='phytoecologyarea',
            name='geometry_type',
            field=models.CharField(blank=True, db_column='tipo_geometria', max_length=50, null=True, verbose_name='Tipo de Geometria'),
        ),
        migrations.AddField(
            model_name='zoningarea',
            name='geometry_type',
            field=models.CharField(blank=True, db_column='tipo_geometria', max_length=50, null=True, verbose_name='Tipo de Geometria'),
        ),
    ]
