# Generated by Django 5.2.8 on 2025-11-18 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_layers', '0006_environmentalprotectionarea_geometry_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndigenousArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.TextField(db_column='coordenadas_geograficas', verbose_name='Coordenadas Geográficas')),
                ('geometry_type', models.CharField(blank=True, db_column='tipo_geometria', max_length=50, null=True, verbose_name='Tipo de Geometria')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte de Dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em')),
                ('indigenous_name', models.CharField(db_column='NOME_AREA', max_length=70, verbose_name='nome da terra indigena')),
                ('hash_id', models.CharField(blank=True, db_column='hash_id', max_length=64, null=True, unique=True, verbose_name='Hash ID')),
                ('created_by', models.ForeignKey(blank=True, db_column='id_criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, db_column='id_atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'terra indigena',
                'verbose_name_plural': 'terras indigenas',
                'db_table': 'tb_area_terra_indigena',
            },
        ),
    ]
