# Generated by Django 5.2.8 on 2025-11-18 23:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_layers', '0007_indigenousarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalprotectionarea',
            name='geometry_new',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_tmp', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='indigenousarea',
            name='geometry_new',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_tmp', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='phytoecologyarea',
            name='geometry_new',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_tmp', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='zoningarea',
            name='geometry_new',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_tmp', null=True, srid=4326),
        ),
    ]
