# Generated by Django 5.2.8 on 2025-11-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_layers', '0008_environmentalprotectionarea_geometry_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentalprotectionarea',
            name='geometry_type',
        ),
        migrations.RemoveField(
            model_name='indigenousarea',
            name='geometry_type',
        ),
        migrations.RemoveField(
            model_name='phytoecologyarea',
            name='geometry_type',
        ),
        migrations.RemoveField(
            model_name='zoningarea',
            name='geometry_type',
        ),
        migrations.AddField(
            model_name='environmentalprotectionarea',
            name='area_ha',
            field=models.FloatField(blank=True, db_column='area_ha', null=True, verbose_name='Área (ha)'),
        ),
        migrations.AddField(
            model_name='environmentalprotectionarea',
            name='area_m2',
            field=models.FloatField(blank=True, db_column='area_m2', null=True, verbose_name='Área (m²)'),
        ),
        migrations.AddField(
            model_name='indigenousarea',
            name='area_ha',
            field=models.FloatField(blank=True, db_column='area_ha', null=True, verbose_name='Área (ha)'),
        ),
        migrations.AddField(
            model_name='indigenousarea',
            name='area_m2',
            field=models.FloatField(blank=True, db_column='area_m2', null=True, verbose_name='Área (m²)'),
        ),
        migrations.AddField(
            model_name='phytoecologyarea',
            name='area_ha',
            field=models.FloatField(blank=True, db_column='area_ha', null=True, verbose_name='Área (ha)'),
        ),
        migrations.AddField(
            model_name='phytoecologyarea',
            name='area_m2',
            field=models.FloatField(blank=True, db_column='area_m2', null=True, verbose_name='Área (m²)'),
        ),
        migrations.AddField(
            model_name='zoningarea',
            name='area_ha',
            field=models.FloatField(blank=True, db_column='area_ha', null=True, verbose_name='Área (ha)'),
        ),
        migrations.AddField(
            model_name='zoningarea',
            name='area_m2',
            field=models.FloatField(blank=True, db_column='area_m2', null=True, verbose_name='Área (m²)'),
        ),
    ]
