# Generated by Django 5.2.8 on 2025-11-19 16:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_layers', '0009_remove_environmentalprotectionarea_geometry_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalprotectionarea',
            name='geometry_new',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_tmp', null=True, srid=4674),
        ),
        migrations.AlterField(
            model_name='indigenousarea',
            name='geometry_new',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_tmp', null=True, srid=4674),
        ),
        migrations.AlterField(
            model_name='phytoecologyarea',
            name='geometry_new',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_tmp', null=True, srid=4674),
        ),
        migrations.AlterField(
            model_name='zoningarea',
            name='geometry_new',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_tmp', null=True, srid=4674),
        ),
    ]
